CREATE TABLE [dbo].[Productos]
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Nombre NVARCHAR(100) NOT NULL,
	Codigo NVARCHAR(100) NOT NULL,
	Categoria NVARCHAR(100) NOT NULL,
	PrecioUnitario DECIMAL(18,2) NOT NULL,
	Cantidad INT NOT NULl,
	StockMinimo INT NOT NULL
)
